// Dữ liệu mẫu — thay bằng nguồn thật (API, JSON, CMS…) khi triển khai thực tế.
// salaryMin/salaryMax tính theo triệu VNĐ/tháng. postedDaysAgo = số ngày trước hôm nay.

const JOBS = [
  {
    id: "CV-1042",
    title: "Lập trình viên Frontend (ReactJS)",
    company: "Vinatech Solutions",
    location: "Hà Nội",
    category: "Công nghệ thông tin",
    type: "Toàn thời gian",
    salaryMin: 18, salaryMax: 28,
    tags: ["React", "TypeScript", "2 năm kinh nghiệm"],
    postedDaysAgo: 1,
    code: "8891"
  },
  {
    id: "CV-1043",
    title: "Nhân viên Kinh doanh B2B",
    company: "Phú Gia Land",
    location: "TP. Hồ Chí Minh",
    category: "Kinh doanh / Sales",
    type: "Toàn thời gian",
    salaryMin: 10, salaryMax: 25,
    tags: ["Hoa hồng cao", "Không cần kinh nghiệm"],
    postedDaysAgo: 0,
    code: "2207"
  },
  {
    id: "CV-1044",
    title: "Chuyên viên Marketing Digital",
    company: "Lá Chuối Media",
    location: "Đà Nẵng",
    category: "Marketing",
    type: "Toàn thời gian",
    salaryMin: 12, salaryMax: 18,
    tags: ["Facebook Ads", "Content", "SEO"],
    postedDaysAgo: 3,
    code: "5510"
  },
  {
    id: "CV-1045",
    title: "Kế toán tổng hợp",
    company: "Công ty CP Dệt May Sông Hồng",
    location: "Hải Phòng",
    category: "Kế toán / Tài chính",
    type: "Toàn thời gian",
    salaryMin: 11, salaryMax: 15,
    tags: ["MISA", "Thuế", "3 năm kinh nghiệm"],
    postedDaysAgo: 5,
    code: "3364"
  },
  {
    id: "CV-1046",
    title: "Công nhân vận hành máy CNC",
    company: "Khu công nghiệp Bắc Ninh — Nhà máy Thăng Long",
    location: "Bắc Ninh",
    category: "Sản xuất / Kỹ thuật",
    type: "Toàn thời gian",
    salaryMin: 9, salaryMax: 13,
    tags: ["Ca kíp", "Đào tạo tại chỗ"],
    postedDaysAgo: 2,
    code: "7729"
  },
  {
    id: "CV-1047",
    title: "Nhân viên chăm sóc khách hàng (Tổng đài)",
    company: "Viettel Contact Center",
    location: "Hà Nội",
    category: "Dịch vụ khách hàng",
    type: "Toàn thời gian",
    salaryMin: 8, salaryMax: 12,
    tags: ["Ca xoay", "Giọng nói tốt"],
    postedDaysAgo: 1,
    code: "1198"
  },
  {
    id: "CV-1048",
    title: "UI/UX Designer",
    company: "Studio Mực Nho",
    location: "Từ xa",
    category: "Thiết kế",
    type: "Từ xa",
    salaryMin: 15, salaryMax: 22,
    tags: ["Figma", "Portfolio yêu cầu"],
    postedDaysAgo: 4,
    code: "4453"
  },
  {
    id: "CV-1049",
    title: "Chuyên viên Nhân sự (C&B)",
    company: "Tập đoàn Hoa Sen",
    location: "TP. Hồ Chí Minh",
    category: "Nhân sự",
    type: "Toàn thời gian",
    salaryMin: 13, salaryMax: 19,
    tags: ["Tính lương", "BHXH"],
    postedDaysAgo: 6,
    code: "9082"
  },
  {
    id: "CV-1050",
    title: "Giáo viên Tiếng Anh (Trung tâm)",
    company: "Anh Ngữ Sao Việt",
    location: "Cần Thơ",
    category: "Giáo dục",
    type: "Bán thời gian",
    salaryMin: 7, salaryMax: 14,
    tags: ["IELTS 7.0+", "Buổi tối"],
    postedDaysAgo: 2,
    code: "6675"
  },
  {
    id: "CV-1051",
    title: "Tài xế giao hàng (xe máy)",
    company: "Giao Hàng Nhanh Chóng",
    location: "Hà Nội",
    category: "Vận tải / Logistics",
    type: "Toàn thời gian",
    salaryMin: 9, salaryMax: 16,
    tags: ["Có xe riêng", "Thu nhập theo đơn"],
    postedDaysAgo: 0,
    code: "3321"
  },
  {
    id: "CV-1052",
    title: "Lập trình viên Backend (Node.js)",
    company: "Fintek Nam Á",
    location: "TP. Hồ Chí Minh",
    category: "Công nghệ thông tin",
    type: "Toàn thời gian",
    salaryMin: 20, salaryMax: 35,
    tags: ["Node.js", "PostgreSQL", "Microservices"],
    postedDaysAgo: 1,
    code: "8845"
  },
  {
    id: "CV-1053",
    title: "Thực tập sinh Marketing",
    company: "Cỏ May Startup",
    location: "Đà Nẵng",
    category: "Marketing",
    type: "Thực tập",
    salaryMin: 3, salaryMax: 5,
    tags: ["Sinh viên năm cuối", "Hỗ trợ xăng xe"],
    postedDaysAgo: 3,
    code: "1120"
  },
  {
    id: "CV-1054",
    title: "Trưởng nhóm Kinh doanh Bất động sản",
    company: "Phú Gia Land",
    location: "TP. Hồ Chí Minh",
    category: "Kinh doanh / Sales",
    type: "Toàn thời gian",
    salaryMin: 20, salaryMax: 40,
    tags: ["Quản lý team", "3 năm kinh nghiệm"],
    postedDaysAgo: 7,
    code: "2298"
  },
  {
    id: "CV-1055",
    title: "Kỹ sư Cơ khí (Bảo trì)",
    company: "Nhà máy Nhiệt điện Vĩnh Tân",
    location: "Bình Thuận",
    category: "Sản xuất / Kỹ thuật",
    type: "Toàn thời gian",
    salaryMin: 14, salaryMax: 20,
    tags: ["AutoCAD", "Bảo trì thiết bị"],
    postedDaysAgo: 5,
    code: "6602"
  },
  {
    id: "CV-1056",
    title: "Nhân viên thu ngân",
    company: "Siêu thị Coop Xanh",
    location: "Hải Phòng",
    category: "Dịch vụ khách hàng",
    type: "Bán thời gian",
    salaryMin: 6, salaryMax: 8,
    tags: ["Ca linh hoạt", "Sinh viên OK"],
    postedDaysAgo: 2,
    code: "4471"
  },
  {
    id: "CV-1057",
    title: "Data Analyst",
    company: "Fintek Nam Á",
    location: "Từ xa",
    category: "Công nghệ thông tin",
    type: "Từ xa",
    salaryMin: 17, salaryMax: 26,
    tags: ["SQL", "Python", "PowerBI"],
    postedDaysAgo: 0,
    code: "8802"
  },
  {
    id: "CV-1058",
    title: "Chuyên viên Content Sáng tạo",
    company: "Lá Chuối Media",
    location: "Hà Nội",
    category: "Marketing",
    type: "Toàn thời gian",
    salaryMin: 10, salaryMax: 16,
    tags: ["Viết lách", "TikTok/Reels"],
    postedDaysAgo: 4,
    code: "5567"
  },
  {
    id: "CV-1059",
    title: "Kiểm toán viên nội bộ",
    company: "Tập đoàn Hoa Sen",
    location: "TP. Hồ Chí Minh",
    category: "Kế toán / Tài chính",
    type: "Toàn thời gian",
    salaryMin: 16, salaryMax: 24,
    tags: ["CPA là lợi thế", "Đi công tác"],
    postedDaysAgo: 8,
    code: "3390"
  },
  {
    id: "CV-1060",
    title: "Quản lý kho vận",
    company: "Giao Hàng Nhanh Chóng",
    location: "Cần Thơ",
    category: "Vận tải / Logistics",
    type: "Toàn thời gian",
    salaryMin: 13, salaryMax: 18,
    tags: ["Quản lý tồn kho", "Excel"],
    postedDaysAgo: 6,
    code: "3345"
  },
  {
    id: "CV-1061",
    title: "Giáo viên Mầm non",
    company: "Trường Mầm non Ánh Dương",
    location: "Hà Nội",
    category: "Giáo dục",
    type: "Toàn thời gian",
    salaryMin: 7, salaryMax: 10,
    tags: ["Yêu trẻ", "Chứng chỉ sư phạm"],
    postedDaysAgo: 3,
    code: "6691"
  },
  {
    id: "CV-1062",
    title: "Đồ hoạ viên (Graphic Designer)",
    company: "Studio Mực Nho",
    location: "Đà Nẵng",
    category: "Thiết kế",
    type: "Toàn thời gian",
    salaryMin: 11, salaryMax: 17,
    tags: ["Photoshop", "Illustrator"],
    postedDaysAgo: 1,
    code: "4409"
  },
  {
    id: "CV-1063",
    title: "Chuyên viên Tuyển dụng",
    company: "Vinatech Solutions",
    location: "Hà Nội",
    category: "Nhân sự",
    type: "Toàn thời gian",
    salaryMin: 12, salaryMax: 17,
    tags: ["IT Recruitment", "LinkedIn"],
    postedDaysAgo: 2,
    code: "9021"
  },
  {
    id: "CV-1064",
    title: "Thợ điện công nghiệp",
    company: "Khu công nghiệp Bắc Ninh — Nhà máy Thăng Long",
    location: "Bắc Ninh",
    category: "Sản xuất / Kỹ thuật",
    type: "Toàn thời gian",
    salaryMin: 10, salaryMax: 15,
    tags: ["Chứng chỉ an toàn điện", "Ca kíp"],
    postedDaysAgo: 9,
    code: "7756"
  },
  {
    id: "CV-1065",
    title: "Thực tập sinh Lập trình",
    company: "Fintek Nam Á",
    location: "TP. Hồ Chí Minh",
    category: "Công nghệ thông tin",
    type: "Thực tập",
    salaryMin: 4, salaryMax: 6,
    tags: ["Java hoặc Python", "Sinh viên năm 3-4"],
    postedDaysAgo: 0,
    code: "8867"
  }
];
